name: Build FPS-Plus

on:
  push:
    branches: [ master ] # Or your default branch, e.g., main
  pull_request:
    branches: [ master ] # Or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: '4.2.5' # Using a specific stable version

    # Add step to display and set environment variables
    - name: Set Haxe environment variables
      run: |
        echo "Setting HAXEPATH..."
        where haxe
        echo "HAXEPATH=%HOMEDRIVE%%HOMEPATH%\haxelib" >> %GITHUB_ENV%
        echo "HAXE_STD_PATH=%HOMEDRIVE%%HOMEPATH%\haxelib\std" >> %GITHUB_ENV%
      shell: cmd

    - name: Install Haxe Module Manager (hmm)
      run: |
        echo "Current HAXEPATH: %HAXEPATH%"
        haxelib --global install hmm
        haxelib --global run hmm setup
      shell: cmd

    - name: Install project dependencies
      run: |
        echo "Current directory:"
        dir
        hmm install
      shell: cmd

    - name: Install hxvlc (if needed)
      run: haxelib --global install hxvlc
      shell: cmd

    - name: Set up Lime
      run: |
        haxelib install lime
        haxelib run lime setup -y
      shell: cmd

    - name: Compile the game for Windows
      run: lime build windows
      shell: cmd
