name: Build FPS-Plus

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install X11 development libraries
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: '4.2.5'

    - name: Install Haxe Module Manager (hmm)
      run: |
        haxelib --global install hmm
        haxelib --global run hmm setup

    - name: Install project dependencies
      run: hmm install

    - name: Install Lime and OpenFL
      run: |
        haxelib install lime
        haxelib install openfl
        haxelib run lime setup -y

    - name: Install hxvlc (if needed)
      run: haxelib --global install hxvlc

    - name: Compile the game for Windows
      run: haxelib run lime build windows
