name: Build Friday Night Funkin FPS Plus (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build FNF FPS Plus (Windows)
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      
      # Windows-specific setup (if needed)
      - name: Setup Windows dependencies
        run: |
          # Visual Studio is pre-installed on the runner
          # Additional Windows dependencies would go here if needed

      - name: Install Haxe dependencies
        run: |
          haxelib --global install hmm
          haxelib --global run hmm setup
          haxelib install hmm
          haxelib run hmm install
          haxelib --global install hxvlc
          haxelib run lime setup

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib list

      - name: Create version file
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "${{github.sha}}" > VERSION

      - name: Build Windows
        run: haxelib run lime build windows -x64 -${{ github.event_name != 'pull_request' && 'final' || 'debug' }}

      - name: Package Windows build
        uses: actions/upload-artifact@v2
        with:
          name: FNF-FPSPlus-Windows-${{ github.run_id }}
          path: export/windows/${{ github.event_name != 'pull_request' && 'final' || 'debug' }}
          if-no-files-found: error
