name: Build Friday Night Funkin FPS Plus

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build FNF FPS Plus (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            arch: x64
            name: linux
          - os: windows-latest
            target: windows
            arch: x64
            name: windows
          - os: macos-latest
            target: mac
            arch: x64
            name: mac
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      
      # Install Linux dependencies
      - name: Install Linux dependencies
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libopenal-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libasound2-dev libpulse-dev

      # Install macOS dependencies
      - name: Install macOS dependencies
        if: matrix.target == 'mac'
        run: brew install openal-soft

      # Install Windows dependencies (if needed)
      # - name: Install Windows dependencies
      #   if: matrix.target == 'windows'
      #   run: |
      #     # Add Windows-specific dependencies here if needed

      - name: Install Haxe dependencies
        run: |
          haxelib --global install hmm
          haxelib --global run hmm setup
          haxelib install hmm
          haxelib run hmm install
          haxelib --global install hxvlc
          haxelib run lime setup

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config MACOSX_DEPLOYMENT_TARGET 10.13
          haxelib list

      - name: Create version file
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "${{github.sha}}" > VERSION

      - name: Build
        run: haxelib run lime build ${{ matrix.target }} -${{ matrix.arch }} -${{ github.event_name != 'pull_request' && 'final' || 'debug' }}

      - name: Package build
        uses: actions/upload-artifact@v2
        with:
          name: FNF-FPSPlus-${{ matrix.name }}-$(date '+%Y%m%d-%H%M%S')
          path: export/${{ matrix.target }}/${{ github.event_name != 'pull_request' && 'final' || 'debug' }}
          if-no-files-found: error

  # Add Android build job if needed
  # build-android:
  #   name: Build FNF FPS Plus (Android)
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Add Android-specific build steps here if required by FPS Plus
